name: Generate java transitive dependency graph
on:
  push:
    branches:
      - "main"
  
permissions:
  contents: write

jobs:
  generate-dependency-graph:
    uses: govuk-pay/pay-ci/.github/workflows/_run-java-transitive-dependency-update.yml@master